// Code generated by mockery v2.43.0. DO NOT EDIT.

package tfexec

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockService is an autogenerated mock type for the service type
type mockService struct {
	mock.Mock
}

type mockService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockService) EXPECT() *mockService_Expecter {
	return &mockService_Expecter{mock: &_m.Mock}
}

// ExecuteDown provides a mock function with given fields: _a0
func (_m *mockService) ExecuteDown(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteDown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockService_ExecuteDown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteDown'
type mockService_ExecuteDown_Call struct {
	*mock.Call
}

// ExecuteDown is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockService_Expecter) ExecuteDown(_a0 interface{}) *mockService_ExecuteDown_Call {
	return &mockService_ExecuteDown_Call{Call: _e.mock.On("ExecuteDown", _a0)}
}

func (_c *mockService_ExecuteDown_Call) Run(run func(_a0 context.Context)) *mockService_ExecuteDown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockService_ExecuteDown_Call) Return(_a0 error) *mockService_ExecuteDown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockService_ExecuteDown_Call) RunAndReturn(run func(context.Context) error) *mockService_ExecuteDown_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteUp provides a mock function with given fields: _a0
func (_m *mockService) ExecuteUp(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockService_ExecuteUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteUp'
type mockService_ExecuteUp_Call struct {
	*mock.Call
}

// ExecuteUp is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockService_Expecter) ExecuteUp(_a0 interface{}) *mockService_ExecuteUp_Call {
	return &mockService_ExecuteUp_Call{Call: _e.mock.On("ExecuteUp", _a0)}
}

func (_c *mockService_ExecuteUp_Call) Run(run func(_a0 context.Context)) *mockService_ExecuteUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockService_ExecuteUp_Call) Return(_a0 error) *mockService_ExecuteUp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockService_ExecuteUp_Call) RunAndReturn(run func(context.Context) error) *mockService_ExecuteUp_Call {
	_c.Call.Return(run)
	return _c
}

// newMockService creates a new instance of mockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockService {
	mock := &mockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
