stages:
  - prepare
  - unit
  - e2e

image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

.go-install:
  before_script:
    - apk add --update --no-cache curl tar bash
    - curl -OL https://golang.org/dl/go1.21.4.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin
    - go version

# Terraform formatting

terraform-formatting:
  stage: prepare
  script:
    - terraform fmt -check -recursive

# AWS unit tests

aws-internal-unit-tests:
  stage: unit
  extends:
    - .go-install
  script:
    - cd modules/aws/internal
    - go test ./... -v

aws-prod-unit-tests:
  stage: unit
  extends:
    - .go-install
  script:
    - cd modules/aws/prod
    - go test ./... -v

aws-dev-unit-tests:
  stage: unit
  extends:
    - .go-install
  script:
    - cd modules/aws/dev
    - go test ./... -v

aws-test-unit-tests:
  stage: unit
  extends:
    - .go-install
  script:
    - cd modules/aws/test
    - go test ./... -v

# Gitlab module tests

gitlab-provider-unit-tests:
  stage: unit
  extends:
    - .go-install
  script:
    - cd modules/gitlab/internal
    - go test ./... -v

# E2E tests

aws-prod-e2e:
  stage: e2e
  extends:
    - .go-install
  script:
    - cd modules/aws/prod
    - go test ./prod_e2e_test.go -tags e2e -timeout 30m
