stages:
  - prepare
  - lint
  - unit
  - e2e

include:
  - local: .gitlab/ci/00_common.gitlab-ci.yml
  - local: .gitlab/ci/00_rules.gitlab-ci.yml
  - local: .gitlab/ci/10_prepare.gitlab-ci.yml
  - local: .gitlab/ci/20_lint.gitlab-ci.yml
  - local: .gitlab/ci/30_unit.gitlab-ci.yml
  - local: .gitlab/ci/31_sast.gitlab-ci.yml
  - local: .gitlab/ci/40_e2e.gitlab-ci.yml
