stages:
  - lint
  - unit
  - e2e

image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

.go-install:
  before_script:
    - apk add --update --no-cache curl tar bash
    - curl -OL https://golang.org/dl/go1.21.4.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin
    - go version

# Linting

terraform-formatting:
  stage: lint
  script:
    - terraform fmt -check -recursive

# Unit tests

unit-tests:
  stage: unit
  extends:
    - .go-install
  script:
    - cd modules
    - go test ./... -v

# E2E tests

aws-prod-e2e:
  stage: e2e
  extends:
    - .go-install
  script:
    - cd e2e/aws
    - go test . -tags e2e -timeout 30m
