stages:
  - lint
  - unit
  - e2e

include:
  - local: .gitlab/ci/00_common.gitlab-ci.yml
  - local: .gitlab/ci/00_rules.gitlab-ci.yml
  - local: .gitlab/ci/10_lint.gitlab-ci.yml
  - local: .gitlab/ci/20_unit.gitlab-ci.yml
  - local: .gitlab/ci/30_e2e.gitlab-ci.yml
