// Code generated by mockery v2.43.0. DO NOT EDIT.

package cli

import (
	context "context"

	cobra "github.com/spf13/cobra"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandExecutor is an autogenerated mock type for the CommandExecutor type
type MockCommandExecutor struct {
	mock.Mock
}

type MockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandExecutor) EXPECT() *MockCommandExecutor_Expecter {
	return &MockCommandExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cmd, args
func (_m *MockCommandExecutor) Execute(ctx context.Context, cmd *cobra.Command, args []string) error {
	ret := _m.Called(ctx, cmd, args)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cobra.Command, []string) error); ok {
		r0 = rf(ctx, cmd, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommandExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *cobra.Command
//   - args []string
func (_e *MockCommandExecutor_Expecter) Execute(ctx interface{}, cmd interface{}, args interface{}) *MockCommandExecutor_Execute_Call {
	return &MockCommandExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, cmd, args)}
}

func (_c *MockCommandExecutor_Execute_Call) Run(run func(ctx context.Context, cmd *cobra.Command, args []string)) *MockCommandExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*cobra.Command), args[2].([]string))
	})
	return _c
}

func (_c *MockCommandExecutor_Execute_Call) Return(_a0 error) *MockCommandExecutor_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_Execute_Call) RunAndReturn(run func(context.Context, *cobra.Command, []string) error) *MockCommandExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandExecutor creates a new instance of MockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandExecutor {
	mock := &MockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
