variables:
  TF_runner_token: ${GITLAB_TOKEN}

stages: [validate, test, build, deploy, runner-test, cleanup]

include:
  - component: gitlab.com/components/opentofu/full-pipeline@0.10.0
    inputs:
      # The version must currently be specified explicitly as an input,
      # to find the correctly associated images. # This can be removed
      # once https://gitlab.com/gitlab-org/gitlab/-/issues/438275 is solved.
      version: 0.18.0-rc5
      opentofu_version: 1.6.1
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml

## This additional test job will run on the newly provisioned runner and verify if everything is working correctly
# This job will be stuck, until the runner is available
# Creating the infrastructure in AWS takes approx. 5 min
runner-test:
  stage: runner-test
  tags:
    - grit-runner
  script:
    - echo "hello runner"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
