// Code generated by mockery v2.43.0. DO NOT EDIT.

package wrapper

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockLoopStatusCheckClient is an autogenerated mock type for the loopStatusCheckClient type
type mockLoopStatusCheckClient struct {
	mock.Mock
}

type mockLoopStatusCheckClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLoopStatusCheckClient) EXPECT() *mockLoopStatusCheckClient_Expecter {
	return &mockLoopStatusCheckClient_Expecter{mock: &_m.Mock}
}

// CheckStatus provides a mock function with given fields: _a0
func (_m *mockLoopStatusCheckClient) CheckStatus(_a0 context.Context) (Status, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CheckStatus")
	}

	var r0 Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (Status, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) Status); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(Status)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockLoopStatusCheckClient_CheckStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckStatus'
type mockLoopStatusCheckClient_CheckStatus_Call struct {
	*mock.Call
}

// CheckStatus is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockLoopStatusCheckClient_Expecter) CheckStatus(_a0 interface{}) *mockLoopStatusCheckClient_CheckStatus_Call {
	return &mockLoopStatusCheckClient_CheckStatus_Call{Call: _e.mock.On("CheckStatus", _a0)}
}

func (_c *mockLoopStatusCheckClient_CheckStatus_Call) Run(run func(_a0 context.Context)) *mockLoopStatusCheckClient_CheckStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockLoopStatusCheckClient_CheckStatus_Call) Return(_a0 Status, _a1 error) *mockLoopStatusCheckClient_CheckStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockLoopStatusCheckClient_CheckStatus_Call) RunAndReturn(run func(context.Context) (Status, error)) *mockLoopStatusCheckClient_CheckStatus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockLoopStatusCheckClient creates a new instance of mockLoopStatusCheckClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLoopStatusCheckClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLoopStatusCheckClient {
	mock := &mockLoopStatusCheckClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
