#cloud-config

groups:
  - ubuntu: [root,sys]
  - hashicorp

users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false

packages:
  - git
  - git-lfs

# https://docs.gitlab.com/runner/install/linux-repository.html
runcmd:
  - curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
  - sudo apt-get install gitlab-runner
  - sudo gitlab-runner register --non-interactive --url "${gitlab_url}" --token "${runner_token}" --executor "shell" --description "grit-test-instance"
