// Code generated by mockery v2.43.0. DO NOT EDIT.

package ssh

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockExecCmd is an autogenerated mock type for the execCmd type
type mockExecCmd struct {
	mock.Mock
}

type mockExecCmd_Expecter struct {
	mock *mock.Mock
}

func (_m *mockExecCmd) EXPECT() *mockExecCmd_Expecter {
	return &mockExecCmd_Expecter{mock: &_m.Mock}
}

// Kill provides a mock function with given fields:
func (_m *mockExecCmd) Kill() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockExecCmd_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type mockExecCmd_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *mockExecCmd_Expecter) Kill() *mockExecCmd_Kill_Call {
	return &mockExecCmd_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *mockExecCmd_Kill_Call) Run(run func()) *mockExecCmd_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockExecCmd_Kill_Call) Return(_a0 error) *mockExecCmd_Kill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockExecCmd_Kill_Call) RunAndReturn(run func() error) *mockExecCmd_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields:
func (_m *mockExecCmd) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockExecCmd_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockExecCmd_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *mockExecCmd_Expecter) Start() *mockExecCmd_Start_Call {
	return &mockExecCmd_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *mockExecCmd_Start_Call) Run(run func()) *mockExecCmd_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockExecCmd_Start_Call) Return(_a0 error) *mockExecCmd_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockExecCmd_Start_Call) RunAndReturn(run func() error) *mockExecCmd_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StderrPipe provides a mock function with given fields:
func (_m *mockExecCmd) StderrPipe() (io.ReadCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StderrPipe")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExecCmd_StderrPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StderrPipe'
type mockExecCmd_StderrPipe_Call struct {
	*mock.Call
}

// StderrPipe is a helper method to define mock.On call
func (_e *mockExecCmd_Expecter) StderrPipe() *mockExecCmd_StderrPipe_Call {
	return &mockExecCmd_StderrPipe_Call{Call: _e.mock.On("StderrPipe")}
}

func (_c *mockExecCmd_StderrPipe_Call) Run(run func()) *mockExecCmd_StderrPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockExecCmd_StderrPipe_Call) Return(_a0 io.ReadCloser, _a1 error) *mockExecCmd_StderrPipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExecCmd_StderrPipe_Call) RunAndReturn(run func() (io.ReadCloser, error)) *mockExecCmd_StderrPipe_Call {
	_c.Call.Return(run)
	return _c
}

// StdinPipe provides a mock function with given fields:
func (_m *mockExecCmd) StdinPipe() (io.WriteCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StdinPipe")
	}

	var r0 io.WriteCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.WriteCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.WriteCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExecCmd_StdinPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StdinPipe'
type mockExecCmd_StdinPipe_Call struct {
	*mock.Call
}

// StdinPipe is a helper method to define mock.On call
func (_e *mockExecCmd_Expecter) StdinPipe() *mockExecCmd_StdinPipe_Call {
	return &mockExecCmd_StdinPipe_Call{Call: _e.mock.On("StdinPipe")}
}

func (_c *mockExecCmd_StdinPipe_Call) Run(run func()) *mockExecCmd_StdinPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockExecCmd_StdinPipe_Call) Return(_a0 io.WriteCloser, _a1 error) *mockExecCmd_StdinPipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExecCmd_StdinPipe_Call) RunAndReturn(run func() (io.WriteCloser, error)) *mockExecCmd_StdinPipe_Call {
	_c.Call.Return(run)
	return _c
}

// StdoutPipe provides a mock function with given fields:
func (_m *mockExecCmd) StdoutPipe() (io.ReadCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StdoutPipe")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExecCmd_StdoutPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StdoutPipe'
type mockExecCmd_StdoutPipe_Call struct {
	*mock.Call
}

// StdoutPipe is a helper method to define mock.On call
func (_e *mockExecCmd_Expecter) StdoutPipe() *mockExecCmd_StdoutPipe_Call {
	return &mockExecCmd_StdoutPipe_Call{Call: _e.mock.On("StdoutPipe")}
}

func (_c *mockExecCmd_StdoutPipe_Call) Run(run func()) *mockExecCmd_StdoutPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockExecCmd_StdoutPipe_Call) Return(_a0 io.ReadCloser, _a1 error) *mockExecCmd_StdoutPipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExecCmd_StdoutPipe_Call) RunAndReturn(run func() (io.ReadCloser, error)) *mockExecCmd_StdoutPipe_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with given fields:
func (_m *mockExecCmd) Wait() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockExecCmd_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type mockExecCmd_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *mockExecCmd_Expecter) Wait() *mockExecCmd_Wait_Call {
	return &mockExecCmd_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *mockExecCmd_Wait_Call) Run(run func()) *mockExecCmd_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockExecCmd_Wait_Call) Return(_a0 error) *mockExecCmd_Wait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockExecCmd_Wait_Call) RunAndReturn(run func() error) *mockExecCmd_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// newMockExecCmd creates a new instance of mockExecCmd. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockExecCmd(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockExecCmd {
	mock := &mockExecCmd{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
