// Code generated by mockery v2.43.0. DO NOT EDIT.

package ssh

import mock "github.com/stretchr/testify/mock"

// mockTestWriteCloser is an autogenerated mock type for the testWriteCloser type
type mockTestWriteCloser struct {
	mock.Mock
}

type mockTestWriteCloser_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTestWriteCloser) EXPECT() *mockTestWriteCloser_Expecter {
	return &mockTestWriteCloser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *mockTestWriteCloser) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockTestWriteCloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockTestWriteCloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockTestWriteCloser_Expecter) Close() *mockTestWriteCloser_Close_Call {
	return &mockTestWriteCloser_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockTestWriteCloser_Close_Call) Run(run func()) *mockTestWriteCloser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTestWriteCloser_Close_Call) Return(_a0 error) *mockTestWriteCloser_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTestWriteCloser_Close_Call) RunAndReturn(run func() error) *mockTestWriteCloser_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *mockTestWriteCloser) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockTestWriteCloser_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type mockTestWriteCloser_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *mockTestWriteCloser_Expecter) Write(p interface{}) *mockTestWriteCloser_Write_Call {
	return &mockTestWriteCloser_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *mockTestWriteCloser_Write_Call) Run(run func(p []byte)) *mockTestWriteCloser_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *mockTestWriteCloser_Write_Call) Return(n int, err error) *mockTestWriteCloser_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockTestWriteCloser_Write_Call) RunAndReturn(run func([]byte) (int, error)) *mockTestWriteCloser_Write_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTestWriteCloser creates a new instance of mockTestWriteCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTestWriteCloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTestWriteCloser {
	mock := &mockTestWriteCloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
