// Code generated by mockery v2.43.0. DO NOT EDIT.

package shutdown

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	wrapper "gitlab.com/gitlab-org/ci-cd/runner-tools/grit/deployer/internal/wrapper"
)

// mockTfClientMux is an autogenerated mock type for the tfClientMux type
type mockTfClientMux struct {
	mock.Mock
}

type mockTfClientMux_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTfClientMux) EXPECT() *mockTfClientMux_Expecter {
	return &mockTfClientMux_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, fn
func (_m *mockTfClientMux) Execute(ctx context.Context, fn wrapper.CallbackFn) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, wrapper.CallbackFn) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockTfClientMux_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockTfClientMux_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - fn wrapper.CallbackFn
func (_e *mockTfClientMux_Expecter) Execute(ctx interface{}, fn interface{}) *mockTfClientMux_Execute_Call {
	return &mockTfClientMux_Execute_Call{Call: _e.mock.On("Execute", ctx, fn)}
}

func (_c *mockTfClientMux_Execute_Call) Run(run func(ctx context.Context, fn wrapper.CallbackFn)) *mockTfClientMux_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(wrapper.CallbackFn))
	})
	return _c
}

func (_c *mockTfClientMux_Execute_Call) Return(_a0 error) *mockTfClientMux_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTfClientMux_Execute_Call) RunAndReturn(run func(context.Context, wrapper.CallbackFn) error) *mockTfClientMux_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTfClientMux creates a new instance of mockTfClientMux. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTfClientMux(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTfClientMux {
	mock := &mockTfClientMux{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
