default:
  image: ${CI_IMAGE}
  interruptible: true
  tags:
    - gitlab-org

variables:
  CI_IMAGE: "${CI_REGISTRY_IMAGE}/ci:20250403"
  GO_VERSION: "1.23.6"
  DOCKER_VERSION: "24.0.9"

.no_cache:
  cache: {}

.no_dependencies:
  dependencies: []

.no_cache_and_dependencies:
  extends:
    - .no_cache
    - .no_dependencies

.go-cache: &go-cache
  variables:
    # build cache on non-main branches
    GOCACHE: $CI_PROJECT_DIR/.gocache-$CI_COMMIT_REF_PROTECTED
    # go module cache is based on go.sum as a cache key
    GOMODCACHE: $CI_PROJECT_DIR/.gomodcache
  cache:
    - key: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
      paths:
        - .gocache-false/
    - key:
        prefix: gomod
        files:
          - go.mod
          - go.sum
      paths:
        - $GOMODCACHE

.tf-cache:
  cache:
    - key: tf-${CI_PIPELINE_ID}
      paths: 
        # TODO: enable terraform caching 
        # - $CI_PROJECT_DIR/**/.terraform
        - $CI_PROJECT_DIR/**/.terraform.lock.hcl

.go-tf-cache:
  <<: *go-cache
  cache:
    - !reference [.go-cache, cache]
    - !reference [.tf-cache, cache]


.docker_in_docker:
  image: docker:${DOCKER_VERSION}-git
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  tags:
    - gitlab-org-docker
