default:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  tags:
    - gitlab-org

variables:
  GO_VERSION: "go1.21.7"

.no_cache:
  cache: {}

.no_dependencies:
  dependencies: []

.no_cache_and_dependencies:
  extends:
    - .no_cache
    - .no_dependencies

.go-install:
  variables:
    GOCACHE: $CI_PROJECT_DIR/.gocache-$CI_COMMIT_REF_PROTECTED
  before_script:
    - apk add --update --no-cache curl tar bash
    - curl -OL https://golang.org/dl/${GO_VERSION}.linux-amd64.tar.gz
    - tar -C /usr/local -xzf ${GO_VERSION}.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin
    - go version
    - mkdir -p "$GOCACHE"
  cache:
    paths:
      - $CI_PROJECT_DIR/.gocache-false/
    key: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
