####################
# Changes patterns #
####################

.code-backstage-patterns: &code-backstage-patterns
  - ".gitlab-ci.yml"
  - ".gitlab/ci/**/*"
  - ".gitattributes"
  - "**/*.tf"
  - "**/*.lock.hcl"
  - "**/*.go"
  - "go.*"
  - ".golangci.yml"
  - "{scripts}/**/*"

.docs-patterns: &docs-patterns
  - ".vale.ini"
  - ".markdownlint-cli2.yaml"
  - "**/*.md"
  - "scripts/lint-docs.sh"

.ci-image-patterns: &ci-image-patterns
  - dockerfiles/ci/**
  - Makefile.ci-image.mk
  - .gitlab/ci/11_build_ci_image.gitlab-ci.yml

.ci-cloud-patterns: &ci-cloud-patterns
  - ci/cloud/**/*

##############
# Conditions #
##############

.if-default-branch: &if-default-branch
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-merge-request-pipeline: &if-merge-request-pipeline
  if: $CI_PIPELINE_SOURCE == "merge_request_event"

.if-not-canonical-namespace: &if-not-canonical-namespace
  if: '$CI_PROJECT_NAMESPACE !~ /^gitlab-org($|\/)/'

.if-stable-release: &if-stable-release
  if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ && $CI_PROJECT_PATH == "gitlab-org/ci-cd/shared-runners/images/aws/grit-images"

#########
# Rules #
#########

.rules:merge_request_pipelines:
  rules:
    - <<: *if-merge-request-pipeline
    - <<: *if-default-branch

.rules:merge_request_pipelines:code:
  rules:
    - <<: *if-not-canonical-namespace
      when: never
    - <<: *if-merge-request-pipeline
      changes: *code-backstage-patterns
    - <<: *if-default-branch
      changes: *code-backstage-patterns

.rules:merge_request_pipelines:e2e:
  rules:
    - <<: *if-not-canonical-namespace
      when: never
    - <<: *if-merge-request-pipeline
      changes: *code-backstage-patterns
    - <<: *if-default-branch
      changes: *code-backstage-patterns

.rules:merge_request_pipelines:docs:
  rules:
    - <<: *if-merge-request-pipeline
      changes: *docs-patterns
    - <<: *if-default-branch
      changes: *docs-patterns

.rules:merge_request_pipelines:build-ci-image:
  rules:
    - <<: *if-merge-request-pipeline
      changes: *ci-image-patterns

.rules:stable-release:
  rules:
    - <<: *if-stable-release
      when: on_success
