# .stage_done is used as a sentinel at stage n for stage n-1 completion,
# so we can kick off builds in later stages without explicitly waiting
# for the completion of the n-1 stage
.stage_done:
  extends:
    - .no_cache_and_dependencies
    - .rules:merge_request_pipelines
  image: alpine:latest
  variables:
    GIT_STRATEGY: none
  script:
    - exit 0
