terraform formatting:
  stage: lint
  extends:
    - .rules:merge_request_pipelines:no_docs
  script:
    - terraform fmt -check -recursive

terraform variables:
  stage: lint
  extends:
    - .rules:merge_request_pipelines:no_docs
    - .go-install
  script:
    - go test -tags lint .

docs lint markdown:
  image: registry.gitlab.com/gitlab-org/gitlab-docs/lint-markdown:alpine-3.19-vale-3.0.7-markdownlint-0.39.0-markdownlint2-0.12.1
  stage: lint
  extends:
    - .rules:merge_request_pipelines
    - .no_cache_and_dependencies
  needs: []
  script:
    # Lint prose and Markdown
    - scripts/lint-docs.sh VALE_MIN_ALERT_LEVEL=error
