include:
  - local: .gitlab/ci/11_build_ci_image.gitlab-ci.yml

terraform init:
  stage: prepare
  needs:
    - job: build CI image
      optional: true
  extends:
    - .rules:merge_request_pipelines:code
    - .tf-cache
  script:
    - make terraform-init -j4 -Oline
