variables:
  CI_IMAGE: "${CI_REGISTRY_IMAGE}/ci:20240802"

build CI image:
  stage: prepare
  extends:
    - .rules:merge_request_pipelines:build-ci-image
    - .docker_in_docker
  script:
    - apk add --no-cache make
    - make build-ci-image
