terraform formatting:
  stage: lint
  extends:
    - .rules:merge_request_pipelines:code
    - .needs_ci_image
  script:
    - make terraform-fmt-check

terraform validate:
  stage: lint
  extends:
    - .rules:merge_request_pipelines:code
    - .tf-cache
  needs:
    - terraform init
  script:
    # terraform init files should exist in cache, but just in case
    - make terraform-init -j4 -Oline
    - make terraform-validate -j2 -Oline

tflint:
  stage: lint
  extends:
    - .rules:merge_request_pipelines:code
    - .tf-cache
  needs:
    - terraform init
  image:
    name: ghcr.io/terraform-linters/tflint:v0.55.1
    entrypoint: ['']
  script:
    - tflint --recursive --config "$(pwd)/.tflint.hcl"

docs lint markdown:
  image: registry.gitlab.com/gitlab-org/gitlab-docs/lint-markdown:alpine-3.20-vale-3.7.1-markdownlint2-0.14.0-lychee-0.15.1
  stage: lint
  extends:
    - .rules:merge_request_pipelines:docs
    - .no_cache_and_dependencies
  variables:
    VALE_MIN_ALERT_LEVEL: error
  script:
    # Lint prose and Markdown
    - make lint-docs

golang lint:
  stage: lint
  extends:
    - .rules:merge_request_pipelines:code
    - .no_dependencies
    - .go-cache
  image: golangci/golangci-lint:v1.63.4-alpine
  script:
    - apk add --no-cache make
    - make lint-go
