terraform formatting:
  stage: lint
  extends:
    - .rules:merge_request_pipelines:code
  script:
    - make terraform-fmt-check

terraform lint:
  stage: lint
  extends:
    - .rules:merge_request_pipelines:code
    - .go-cache
  script:
    - make lint-terraform

docs lint markdown:
  image: registry.gitlab.com/gitlab-org/gitlab-docs/lint-markdown:alpine-3.20-vale-3.6.1-markdownlint2-0.13.0-lychee-0.15.1
  stage: lint
  extends:
    - .rules:merge_request_pipelines:docs
    - .no_cache_and_dependencies
  needs: []
  variables:
    VALE_MIN_ALERT_LEVEL: error
  script:
    # Lint prose and Markdown
    - make lint-docs

golang lint:
  image: registry.gitlab.com/gitlab-org/ci-cd/runner-tools/runner-linters:1.59.1-go1.22.5-alpine
  stage: lint
  extends:
    - .rules:merge_request_pipelines:code
    - .go-cache
  script:
    - make lint-go
