terraform formatting:
  stage: lint
  extends:
    - .rules:merge_request_pipelines:code
  script:
    - make terraform-fmt-check

docs lint markdown:
  image: registry.gitlab.com/gitlab-org/gitlab-docs/lint-markdown:alpine-3.20-vale-3.7.1-markdownlint2-0.14.0-lychee-0.15.1
  stage: lint
  extends:
    - .rules:merge_request_pipelines:docs
    - .no_cache_and_dependencies
  needs: []
  variables:
    VALE_MIN_ALERT_LEVEL: error
  script:
    # Lint prose and Markdown
    - make lint-docs

golang lint:
  image: golangci/golangci-lint:v1.63.4-alpine
  stage: lint
  extends:
    - .rules:merge_request_pipelines:code
    - .go-cache
  script:
    - apk add --no-cache make
    - make lint-go
