include:
  - local: .gitlab/ci/31_sast.gitlab-ci.yml

.unit_tests:
  stage: unit
  extends:
    - .rules:merge_request_pipelines:code
    - .needs_ci_image
  script:
    - mage test:unit ${UNIT_TEST_EXECUTION_PATH}
  coverage: '/Coverage TOTAL: ([0-9]+\.[0-9]+%)/'
  artifacts:
    when: always
    paths:
      - ${UNIT_TEST_EXECUTION_PATH}/junit.xml
      - ${UNIT_TEST_EXECUTION_PATH}/coverage.txt
    reports:
      junit: ${UNIT_TEST_EXECUTION_PATH}/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: ${UNIT_TEST_EXECUTION_PATH}/coverage.xml

unit tests:
  extends:
    - .unit_tests
    - .go-tf-cache
  needs:
    - terraform init
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_CREDENTIALS_B64}.decoded
    UNIT_TEST_EXECUTION_PATH: ${CI_PROJECT_DIR}
  before_script:
    - cat "${GOOGLE_CREDENTIALS_B64}" | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"

deployer:unit tests:
  extends:
    - .unit_tests
    - .go-cache
  variables:
    UNIT_TEST_EXECUTION_PATH: ${CI_PROJECT_DIR}/deployer
