unit tests:
  stage: unit
  extends:
    - .rules:merge_request_pipelines:no_docs
    - .go-cache
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_CREDENTIALS_B64}.decoded
  script:
    - cat "${GOOGLE_CREDENTIALS_B64}" | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"
    - cd modules
    - go test ./... -v
