unit tests:
  stage: unit
  needs: [terraform formatting]
  extends:
    - .rules:merge_request_pipelines:code
    - .go-cache
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_CREDENTIALS_B64}.decoded
  script:
    - cat "${GOOGLE_CREDENTIALS_B64}" | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"
    - make test
