include:
  - local: .gitlab/ci/31_sast.gitlab-ci.yml

unit tests:
  stage: unit
  needs:
    - job: prepare done
    - job: terraform init
  extends:
    - .rules:merge_request_pipelines:code
    - .go-tf-cache
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_CREDENTIALS_B64}.decoded
  script:
    - cat "${GOOGLE_CREDENTIALS_B64}" | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"
    - make test
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml
