deployer:build:
  stage: build
  extends:
    - .rules:merge_request_pipelines:code
  needs:
    - terraform init
  script:
    - mage deployer:compileFor "linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64"
  artifacts:
    paths:
      - deployer/build/*
