e2e:prod:aws:
  stage: e2e
  needs: []
  extends:
    - .rules:merge_request_pipelines:code
    - .go-cache
  resource_group: e2e-prod-aws
  script:
    - cd e2e/aws
    - go test . -tags e2e -timeout 30m
