e2e:prod:aws:
  stage: e2e
  needs: []
  extends:
    - .rules:merge_request_pipelines:e2e
    - .rules:only_upstream
    - .go-cache
  resource_group: e2e-prod
  script:
    - go test ./e2e/aws -tags e2e -timeout 30m

e2e:prod:google:
  stage: e2e
  needs: []
  extends:
    - .rules:merge_request_pipelines:e2e
    - .rules:only_upstream
    - .go-cache
  resource_group: e2e-prod
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_CREDENTIALS_B64}.decoded
  script:
    - cat "${GOOGLE_CREDENTIALS_B64}" | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"
    - go test ./e2e/google -tags e2e -timeout 1h

e2e:prod:gke:windows:
  stage: e2e
  timeout: 90m
  needs: []
  extends:
    - .rules:merge_request_pipelines:code
    - .go-cache
  resource_group: e2e-prod
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_CREDENTIALS_B64}.decoded
    FF_TIMESTAMPS: true
  script:
    - cat "${GOOGLE_CREDENTIALS_B64}" | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"
    - go test ./e2e/google/steps/gke-windows -tags e2e -timeout ${CI_JOB_TIMEOUT}s
