e2e:
  stage: e2e
  extends:
    - .rules:merge_request_pipelines:e2e
  variables:
    E2E_TEST_ID: ${CI_PIPELINE_ID}
  parallel:
    # Note: generated job names are limited to 255 characters which include
    # variable values.
    # Create a separate trigger job if you need larger inputs.
    matrix:
      - E2E_TEST_NAME: aws
        E2E_TEST_DIR: e2e/aws
        E2E_TEST_IMAGE: alpine/curl:latest
        E2E_TEST_SCRIPT: 'curl http://169.254.169.254/latest/meta-data/instance-id'
      - E2E_TEST_NAME: aws-arm
        E2E_TEST_DIR: e2e/aws
        TF_VAR_ami_arch: arm64
        E2E_TEST_IMAGE: alpine/curl:latest
        E2E_TEST_SCRIPT: 'curl http://169.254.169.254/latest/meta-data/instance-id'
      - E2E_TEST_NAME: google
        E2E_TEST_DIR: e2e/google
        E2E_TEST_IMAGE: alpine/curl:latest
        E2E_TEST_SCRIPT: 'curl -s -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/name'
      - E2E_TEST_NAME: gke-win
        E2E_TEST_DIR: e2e/google/gke-windows
        E2E_TEST_IMAGE: gitlab/gitlab-runner-helper:x86_64-latest-servercore1809
        E2E_TEST_SCRIPT: 'curl "http://169.254.169.254/computeMetadata/v1/instance/name" -Headers @{"Metadata-Flavor"="Google"} -UseBasicParsing'
        E2E_TEST_POWERSHELL: y
  trigger:
    include: .gitlab/ci/e2e-pipeline.gitlab-ci.yml
    strategy: depend
