deployer:upload:
  stage: release
  extends:
    - .rules:after-merge
    - .rules:stable-release
  needs:
    - deployer:build
  script:
    - mage deployer:upload
  artifacts:
    paths:
      - artifacts_list.json

prerelease tag on main:
  stage: release
  extends:
    - .rules:after-merge
    - .no_cache_and_dependencies
  script:
    - ./ci/prerelease-tag.sh

# This job is invoked when a new stable release tag is applied. This job then associates the new tag with a new release.
stable release:
  stage: release
  extends:
    - .rules:stable-release
  needs:
    - deployer:upload
  image: registry.gitlab.com/gitlab-org/cli:latest
  variables:
    CHANGELOG: https://gitlab.com/gitlab-org/ci-cd/runner-tools/grit/blob/$CI_COMMIT_TAG/CHANGELOG.md
    CI_PROJECT_ID: 48756626
  environment:
    name: stable/gitlab
    url: https://gitlab.com/gitlab-org/ci-cd/runner-tools/grit/-/releases
  script:
    - ./scripts/release.sh ${CI_COMMIT_TAG} artifacts_list.json
